"""Add ondelete cascade to student_id in exit_logs

Revision ID: 30887edec354
Revises: 97563eaed938
Create Date: 2024-09-05 15:07:28.513454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30887edec354'
down_revision = '97563eaed938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('exit_logs_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'], ondelete='CASCADE')

    with op.batch_alter_table('lib_logs', schema=None) as batch_op:
        batch_op.drop_constraint('lib_logs_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'], ondelete='CASCADE')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('students_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'laptops', ['laptop_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('students_ibfk_1', 'laptops', ['laptop_id'], ['id'])

    with op.batch_alter_table('lib_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('lib_logs_ibfk_1', 'students', ['student_id'], ['student_id'])

    with op.batch_alter_table('exit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exit_logs_ibfk_1', 'students', ['student_id'], ['student_id'])

    # ### end Alembic commands ###
