"""some additional column in student 'timestamp'

Revision ID: 87bc10aa12b5
Revises: be1395a7c28e
Create Date: 2024-09-01 06:06:50.037167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87bc10aa12b5'
down_revision = 'be1395a7c28e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_library_time', sa.Interval(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('total_library_time')

    # ### end Alembic commands ###
