"""adding new table "exit_logs" and change "logs" to "lib_logs"

Revision ID: 97563eaed938
Revises: 87bc10aa12b5
Create Date: 2024-09-02 04:32:40.917690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97563eaed938'
down_revision = '87bc10aa12b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exit_logs')
    # ### end Alembic commands ###
