"""Add Laptop model and relationships

Revision ID: b24661dba83b
Revises: 933a12a1367f
Create Date: 2024-08-26 06:04:14.323873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b24661dba83b'
down_revision = '933a12a1367f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laptops',
    sa.Column('laptop_unique_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('laptop_unique_id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laptop_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'laptops', ['laptop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('laptop_id')

    op.drop_table('laptops')
    # ### end Alembic commands ###
